"""Runs the shell script generated by Helpers/SettingsPaths.js for real, in a temp dir.

Needs node to evaluate the JS helper; skipped when node isn't installed.
"""

import json
import pathlib
import shutil
import subprocess
import tempfile
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[2]
HELPER = ROOT / "Helpers" / "SettingsPaths.js"


def call_helper(fn, *args):
    # Strip the QML-only pragma and expose the functions to node
    source = HELPER.read_text(encoding="utf-8").replace(".pragma library", "")
    program = source + f"\nprocess.stdout.write(JSON.stringify({fn}(...{json.dumps(list(args))})));"
    out = subprocess.run(["node", "-e", program], check=True, capture_output=True, text=True)
    return json.loads(out.stdout)


@unittest.skipIf(shutil.which("node") is None, "node not installed")
class PrepareScriptTests(unittest.TestCase):
    def setUp(self):
        self.tmp = pathlib.Path(tempfile.mkdtemp(prefix="noctalia settings 'q' "))
        self.config = self.tmp / "config"
        self.cache = self.tmp / "cache"

    def tearDown(self):
        shutil.rmtree(self.tmp)

    def prepare(self, host, seed=True):
        config_dir = str(self.config) + "/"
        settings_dir = call_helper("settingsDir", config_dir)
        target = call_helper("resolveSettingsFile", "", config_dir, host)
        legacy = call_helper("legacySettingsFile", config_dir) if seed else ""
        script = call_helper("prepareScript", [config_dir, str(self.cache) + "/", settings_dir], target, legacy)
        subprocess.run(["sh", "-c", script], check=True)
        return pathlib.Path(target)

    def test_fresh_install_creates_dirs_without_settings(self):
        target = self.prepare("laptop")
        self.assertTrue((self.config / "settings").is_dir())
        self.assertTrue(self.cache.is_dir())
        self.assertFalse(target.exists())  # the shell writes defaults + opens the setup wizard

    def test_legacy_file_seeds_new_host_and_is_kept(self):
        self.config.mkdir(parents=True)
        (self.config / "settings.json").write_text('{"bar": {"barType": "notch"}}')
        target = self.prepare("laptop")
        self.assertEqual(target, self.config / "settings" / "laptop.json")
        self.assertEqual(json.loads(target.read_text())["bar"]["barType"], "notch")
        self.assertTrue((self.config / "settings.json").exists())

    def test_existing_host_file_is_never_overwritten(self):
        (self.config / "settings").mkdir(parents=True)
        (self.config / "settings.json").write_text('{"from": "legacy"}')
        (self.config / "settings" / "laptop.json").write_text('{"from": "host"}')
        target = self.prepare("laptop")
        self.assertEqual(json.loads(target.read_text()), {"from": "host"})

    def test_hosts_get_separate_files(self):
        self.config.mkdir(parents=True)
        (self.config / "settings.json").write_text('{"v": 1}')
        desk = self.prepare("desk")
        desk.write_text('{"v": 2}')
        laptop = self.prepare("laptop")
        self.assertEqual(json.loads(laptop.read_text()), {"v": 1})
        self.assertEqual(json.loads(desk.read_text()), {"v": 2})

    def test_hostile_host_name_stays_inside_settings_dir(self):
        target = self.prepare("../../evil'; touch pwned; '")
        self.assertEqual(target.parent, self.config / "settings")
        self.assertFalse((self.tmp / "pwned").exists())
        self.assertFalse(pathlib.Path("pwned").exists())

    def test_symlinked_legacy_file_is_copied_as_content(self):
        self.config.mkdir(parents=True)
        real = self.tmp / "store-settings.json"
        real.write_text('{"nix": true}')
        (self.config / "settings.json").symlink_to(real)
        target = self.prepare("laptop")
        self.assertFalse(target.is_symlink())
        self.assertEqual(json.loads(target.read_text()), {"nix": True})

    def test_no_seed_when_disabled(self):
        self.config.mkdir(parents=True)
        (self.config / "settings.json").write_text("{}")
        target = self.prepare("laptop", seed=False)
        self.assertFalse(target.exists())


if __name__ == "__main__":
    unittest.main()
